// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe9CFxcEiZkEqZ05U8lxAlGx6baE_wWJo',
    appId: '1:340094353356:web:079d00a9929a29684d6769',
    messagingSenderId: '340094353356',
    projectId: 'basketco-5b3c2',
    authDomain: 'basketco-5b3c2.firebaseapp.com',
    storageBucket: 'basketco-5b3c2.appspot.com',
    measurementId: 'G-ZLTE0CE17V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtP45AaLXAggQzTzbP4o2piBQe19ZPjOc',
    appId: '1:340094353356:android:022865f54b26aecf4d6769',
    messagingSenderId: '340094353356',
    projectId: 'basketco-5b3c2',
    storageBucket: 'basketco-5b3c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBifm8gEa3ZAmVOvN1zVf44-sICkUEI-z8',
    appId: '1:340094353356:ios:7601d3982b862a4a4d6769',
    messagingSenderId: '340094353356',
    projectId: 'basketco-5b3c2',
    storageBucket: 'basketco-5b3c2.appspot.com',
    iosBundleId: 'com.example.basketco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBifm8gEa3ZAmVOvN1zVf44-sICkUEI-z8',
    appId: '1:340094353356:ios:7601d3982b862a4a4d6769',
    messagingSenderId: '340094353356',
    projectId: 'basketco-5b3c2',
    storageBucket: 'basketco-5b3c2.appspot.com',
    iosBundleId: 'com.example.basketco',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBe9CFxcEiZkEqZ05U8lxAlGx6baE_wWJo',
    appId: '1:340094353356:web:74bee2f41f3d954d4d6769',
    messagingSenderId: '340094353356',
    projectId: 'basketco-5b3c2',
    authDomain: 'basketco-5b3c2.firebaseapp.com',
    storageBucket: 'basketco-5b3c2.appspot.com',
    measurementId: 'G-0GSMFZK90H',
  );
}
